--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期三, 24 九月, 2014 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 


--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SsoConfiguration_Configuration') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SsoConfigurationMessage DROP CONSTRAINT FK_SsoConfiguration_Configuration
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SsoConfigurationMessage_Message') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SsoConfigurationMessage DROP CONSTRAINT FK_SsoConfigurationMessage_Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Message_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Message DROP CONSTRAINT FK_Message_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Message_Event') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Message DROP CONSTRAINT FK_Message_Event
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_PublishEvent_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.PublishEvent DROP CONSTRAINT FK_PublishEvent_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Event_PublishEvent') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Event DROP CONSTRAINT FK_Event_PublishEvent
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Event_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Event DROP CONSTRAINT FK_Event_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_IDTransfer_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.IDTransfer DROP CONSTRAINT FK_IDTransfer_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_IDTransfer_DataCeter') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.IDTransfer DROP CONSTRAINT FK_IDTransfer_DataCeter
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_IDTransfer_Base_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.IDTransfer DROP CONSTRAINT FK_IDTransfer_Base_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_DataCeter_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.DataCeter DROP CONSTRAINT FK_DataCeter_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Application_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Application DROP CONSTRAINT FK_Application_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Application_Configuration') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Application DROP CONSTRAINT FK_Application_Configuration
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Configuration_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Configuration DROP CONSTRAINT FK_Configuration_Base
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.SsoConfigurationMessage') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.SsoConfigurationMessage
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.Message') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.PublishEvent') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.PublishEvent
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.Event') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.Event
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.IDTransfer') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.IDTransfer
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.DataCeter') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.DataCeter
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Application') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Application
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Configuration') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Configuration
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.Base') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.Base
;


--  Create Tables 
CREATE TABLE dist.SsoConfigurationMessage ( 
	MessageId uniqueidentifier NOT NULL,    --  分发的消息标识。关联到dist.Message表。 
	ConfigId uniqueidentifier NOT NULL,    --  SSO配置标识。关联到sso.Configuration表。 
	ConfigName nvarchar(256) NOT NULL,    --  配置名称。 
	StartOpenAPI bit NOT NULL,    --  是否启用开放式API。 
	CanInherit bit DEFAULT 1 NOT NULL,    --  是否可以继承。 
	BaseId uniqueidentifier,    --  继承自的配置标识。 
	TokenMark varchar(32) NOT NULL,    --  令牌标记名称。 
	TokenExpiredMins int DEFAULT 30 NOT NULL,    --  令牌失效分钟数。 
	SsoRequired bit NOT NULL,    --  SSO验证是否是必须的。 
	ShowRegisterLink bit NOT NULL,    --  是否显示注册链接。 
	RegisterLinkUrl varchar(1024),    --  注册链接地址。 
	DefaultLanguage int DEFAULT 2052 NOT NULL,    --  默认语言。 
	Action char(1) DEFAULT 'C' NOT NULL    --  消息的动作。'C':创建;‘U'：更新；'R'：逻辑移除；'D'：物理移除。 
)
;

CREATE TABLE dist.Message ( 
	Id uniqueidentifier NOT NULL,    --  消息标识。关联到core.Base表。 
	EventId uniqueidentifier NOT NULL,    --  关联的事件表示。关联到dist.Event表。 
	Completed bit DEFAULT 1 NOT NULL    --  是否准备完毕。1/0。 
)
;

CREATE TABLE dist.PublishEvent ( 
	Id uniqueidentifier NOT NULL,    --  分发事件类型唯一标识。关联到core.Base表。 
	CmdTemplate varchar(max) NOT NULL    --  SQL命令模板。 
)
;

CREATE TABLE dist.Event ( 
	Id uniqueidentifier NOT NULL,    --  分发事件标识。 
	TypeId uniqueidentifier NOT NULL,    --  分发事件类型标识。关联到dist.PublishEvent表。 
	Cmd varchar(max) NOT NULL    --  获取分发数据的SQL命令文本。 
)
;

CREATE TABLE core.IDTransfer ( 
	Id uniqueidentifier NOT NULL,    --  转移关系标识。关联到core.Base表。 
	CenterId uniqueidentifier NOT NULL,    --  数据中心标识。关联到core.DataCenter表。 
	SourceId uniqueidentifier NOT NULL,    --  原始的标识。 
	InternalId uniqueidentifier NOT NULL    --  在当前数据中心中的标识。关联到core.Base表。 
)
;

CREATE TABLE core.DataCeter ( 
	Id uniqueidentifier NOT NULL,    --  数据中心在本机中的标识。关联到core.Base表。 
	Code varchar(64) NOT NULL,    --  数据中心英文代码。 
	IsGlobal bit DEFAULT 0 NOT NULL,    --  是否为总数据中心。1/0。只能有一个总数据中心。 
	Mac varchar(128) NOT NULL    --  总数据中心的MAC地址。 
)
;

CREATE TABLE sso.Application ( 
	Id uniqueidentifier NOT NULL,    --  应用信息标识。关联到core.Base表。 
	ConfigId uniqueidentifier NOT NULL,    --  SSO配置标识。关联到sso.Configuration表。 
	AppName nvarchar(128) NOT NULL,    --  应用名称。 
	IsBeta bit DEFAULT 0 NOT NULL,    --  是否为测试版的应用。1/0。 
	EmailOfService varchar(512) NOT NULL    --  用于获取服务信息的邮件地址。 
)
;

CREATE TABLE sso.Configuration ( 
	Id uniqueidentifier NOT NULL,    --  配置信息标识。关联到core.Base表。 
	ConfigName nvarchar(256) NOT NULL,    --  配置标识名称。 
	StartOpenAPI bit DEFAULT 1 NOT NULL,    --  是否启用开放API访问。1/0。 
	IsPrivate bit DEFAULT 0 NOT NULL,    --  是否为私有配置。1/0。 
	CanInherit bit DEFAULT 1 NOT NULL,    --  是否可以继承。1/0。 
	BaseId uniqueidentifier DEFAULT NULL,    --  继承的配置标识。 
	TokenMark varchar(32) NOT NULL,    --  用于保存令牌数据的键名称。 
	TokenExpiredMins int DEFAULT 30 NOT NULL,    --  令牌超时分钟数。 
	SsoRequired bit DEFAULT 1 NOT NULL,    --  退出后，下次必须重新登录。 
	ShowRegisterLink bit DEFAULT 1 NOT NULL,    --  是否显示注册链接。 
	RegisterLinkUrl varchar(1024) DEFAULT NULL,    --  注册链接地址。 
	DefaultLanguage int DEFAULT 2052 NOT NULL    --  默认的语言LCID。 
)
;

CREATE TABLE core.Base ( 
	Id uniqueidentifier DEFAULT Newid() NOT NULL,    --  对象唯一标识。 
	PublicId varchar(256) NOT NULL,    --  对象的开放标识。 
	Enabled bit DEFAULT 1 NOT NULL,    --  是否可用。1/0。 
	IsRemoved bit DEFAULT 0 NOT NULL,    --  是否已经被逻辑移除。1/0。 
	Visible bit DEFAULT 1 NOT NULL,    --  是否可见。1/0。 
	IsDefault bit DEFAULT 1 NOT NULL,    --  是否为默认的对象。1/0。 
	Actived bit DEFAULT 1 NOT NULL,    --  是否已经被激活。 
	SortId int DEFAULT 0 NOT NULL,    --  排序标记。 
	Version decimal(19,2) DEFAULT 1.00 NOT NULL,    --  版本号。 
	IsLocked bit DEFAULT 0 NOT NULL,    --  是否被锁定。1/0。 
	IsFrozen bit DEFAULT 0 NOT NULL,    --  是否被冻结。 
	CreatedTime datetime DEFAULT Getdate() NOT NULL,    --  对象的创建时间。 
	LastModifiedTime datetime DEFAULT Getdate() NOT NULL,    --  最后一次被修改的时间。 
	ModifiedTimes int DEFAULT 0 NOT NULL,    --  对象信息被修改的次数。 
	ExtendedAttributes xml DEFAULT NULL,    --  扩展的属性。 
	CompatibleExtendedAttributes nvarchar(max) DEFAULT NULL,    --  为了保证兼容性的扩展属性。 
	Description nvarchar(max) DEFAULT NULL,    --  描述信息。 
	Comments nvarchar(max) DEFAULT NULL    --  备注信息。 
)
;


--  Create Indexes 
CREATE INDEX IXFK_SsoConfiguration_Configuration
	ON dist.SsoConfigurationMessage (ConfigId ASC)
;

CREATE INDEX IXFK_SsoConfigurationMessage_Message
	ON dist.SsoConfigurationMessage (MessageId ASC)
;

ALTER TABLE dist.Message
	ADD CONSTRAINT UQ_Message_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Message_Base
	ON dist.Message (Id ASC)
;

CREATE INDEX IXFK_Message_Event
	ON dist.Message (EventId ASC)
;

ALTER TABLE dist.PublishEvent
	ADD CONSTRAINT UQ_PublishEvent_Id UNIQUE (Id)
;

CREATE INDEX IXFK_PublishEvent_Base
	ON dist.PublishEvent (Id ASC)
;

CREATE INDEX IXFK_Event_PublishEvent
	ON dist.Event (TypeId ASC)
;

ALTER TABLE dist.Event
	ADD CONSTRAINT UQ_Event_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Event_Base
	ON dist.Event (Id ASC)
;

ALTER TABLE core.IDTransfer
	ADD CONSTRAINT UQ_IDTransfer_Id UNIQUE (Id)
;

CREATE INDEX IXFK_IDTransfer_Base
	ON core.IDTransfer (Id ASC)
;

CREATE INDEX IXFK_IDTransfer_DataCeter
	ON core.IDTransfer (CenterId ASC)
;

CREATE INDEX IXFK_IDTransfer_Base_02
	ON core.IDTransfer (InternalId ASC)
;

ALTER TABLE core.DataCeter
	ADD CONSTRAINT UQ_DataCeter_Code UNIQUE (Code)
;

ALTER TABLE core.DataCeter
	ADD CONSTRAINT UQ_DataCeter_Id UNIQUE (Id)
;

CREATE INDEX IXFK_DataCeter_Base
	ON core.DataCeter (Id ASC)
;

ALTER TABLE core.DataCeter
	ADD CONSTRAINT UQ_DataCeter_Mac UNIQUE (Mac)
;

ALTER TABLE sso.Application
	ADD CONSTRAINT UQ_Application_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Application_Base
	ON sso.Application (Id ASC)
;

CREATE INDEX IXFK_Application_Configuration
	ON sso.Application (ConfigId ASC)
;

ALTER TABLE sso.Application
	ADD CONSTRAINT UQ_Application_AppName UNIQUE (AppName)
;

ALTER TABLE sso.Configuration
	ADD CONSTRAINT UQ_Configuration_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Configuration_Base
	ON sso.Configuration (Id ASC)
;

ALTER TABLE sso.Configuration
	ADD CONSTRAINT UQ_Configuration_ConfigMark UNIQUE (ConfigName)
;

ALTER TABLE core.Base
	ADD CONSTRAINT UQ_Base_Id UNIQUE (Id)
;

--  Create Primary Key Constraints 
ALTER TABLE dist.SsoConfigurationMessage ADD CONSTRAINT PK_SsoConfiguration 
	PRIMARY KEY CLUSTERED (MessageId)
;

ALTER TABLE dist.Message ADD CONSTRAINT PK_Message 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.PublishEvent ADD CONSTRAINT PK_PublishEvent 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.Event ADD CONSTRAINT PK_Event 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT PK_IDTransfer 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE core.DataCeter ADD CONSTRAINT PK_DataCeter 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE sso.Application ADD CONSTRAINT PK_Application 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE sso.Configuration ADD CONSTRAINT PK_Configuration 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE core.Base ADD CONSTRAINT PK_Base 
	PRIMARY KEY CLUSTERED (Id)
;



--  Create Foreign Key Constraints 
ALTER TABLE dist.SsoConfigurationMessage ADD CONSTRAINT FK_SsoConfiguration_Configuration 
	FOREIGN KEY (ConfigId) REFERENCES sso.Configuration (Id)
;

ALTER TABLE dist.SsoConfigurationMessage ADD CONSTRAINT FK_SsoConfigurationMessage_Message 
	FOREIGN KEY (MessageId) REFERENCES dist.Message (Id)
;

ALTER TABLE dist.Message ADD CONSTRAINT FK_Message_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.Message ADD CONSTRAINT FK_Message_Event 
	FOREIGN KEY (EventId) REFERENCES dist.Event (Id)
;

ALTER TABLE dist.PublishEvent ADD CONSTRAINT FK_PublishEvent_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.Event ADD CONSTRAINT FK_Event_PublishEvent 
	FOREIGN KEY (TypeId) REFERENCES dist.PublishEvent (Id)
;

ALTER TABLE dist.Event ADD CONSTRAINT FK_Event_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT FK_IDTransfer_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT FK_IDTransfer_DataCeter 
	FOREIGN KEY (CenterId) REFERENCES core.DataCeter (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT FK_IDTransfer_Base_02 
	FOREIGN KEY (InternalId) REFERENCES core.Base (Id)
;

ALTER TABLE core.DataCeter ADD CONSTRAINT FK_DataCeter_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Application ADD CONSTRAINT FK_Application_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Application ADD CONSTRAINT FK_Application_Configuration 
	FOREIGN KEY (ConfigId) REFERENCES sso.Configuration (Id)
;

ALTER TABLE sso.Configuration ADD CONSTRAINT FK_Configuration_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;









EXEC sp_addextendedproperty 'MS_Description', 'SSO配置分发消息表。仅分发公开的SSO的配置。', 'Schema', dist, 'table', SsoConfigurationMessage
;
EXEC sp_addextendedproperty 'MS_Description', '分发的消息标识。关联到dist.Message表。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', MessageId
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置标识。关联到sso.Configuration表。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', ConfigId
;

EXEC sp_addextendedproperty 'MS_Description', '配置名称。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', ConfigName
;

EXEC sp_addextendedproperty 'MS_Description', '是否启用开放式API。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', StartOpenAPI
;

EXEC sp_addextendedproperty 'MS_Description', '是否可以继承。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', CanInherit
;

EXEC sp_addextendedproperty 'MS_Description', '继承自的配置标识。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', BaseId
;

EXEC sp_addextendedproperty 'MS_Description', '令牌标记名称。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', TokenMark
;

EXEC sp_addextendedproperty 'MS_Description', '令牌失效分钟数。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', TokenExpiredMins
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO验证是否是必须的。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', SsoRequired
;

EXEC sp_addextendedproperty 'MS_Description', '是否显示注册链接。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', ShowRegisterLink
;

EXEC sp_addextendedproperty 'MS_Description', '注册链接地址。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', RegisterLinkUrl
;

EXEC sp_addextendedproperty 'MS_Description', '默认语言。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', DefaultLanguage
;

EXEC sp_addextendedproperty 'MS_Description', '消息的动作。''C'':创建;‘U''：更新；''R''：逻辑移除；''D''：物理移除。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', Action
;

EXEC sp_addextendedproperty 'MS_Description', '分发事件基本消息数据。', 'Schema', dist, 'table', Message
;
EXEC sp_addextendedproperty 'MS_Description', '消息标识。关联到core.Base表。', 'Schema', dist, 'table', Message, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '关联的事件表示。关联到dist.Event表。', 'Schema', dist, 'table', Message, 'column', EventId
;

EXEC sp_addextendedproperty 'MS_Description', '是否准备完毕。1/0。', 'Schema', dist, 'table', Message, 'column', Completed
;

EXEC sp_addextendedproperty 'MS_Description', '对外发布的分发事件类型。', 'Schema', dist, 'table', PublishEvent
;
EXEC sp_addextendedproperty 'MS_Description', '分发事件类型唯一标识。关联到core.Base表。', 'Schema', dist, 'table', PublishEvent, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', 'SQL命令模板。', 'Schema', dist, 'table', PublishEvent, 'column', CmdTemplate
;

EXEC sp_addextendedproperty 'MS_Description', '数据分发事件表。', 'Schema', dist, 'table', Event
;
EXEC sp_addextendedproperty 'MS_Description', '分发事件标识。', 'Schema', dist, 'table', Event, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '分发事件类型标识。关联到dist.PublishEvent表。', 'Schema', dist, 'table', Event, 'column', TypeId
;

EXEC sp_addextendedproperty 'MS_Description', '获取分发数据的SQL命令文本。', 'Schema', dist, 'table', Event, 'column', Cmd
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心对象标识转移关系表。', 'Schema', core, 'table', IDTransfer
;
EXEC sp_addextendedproperty 'MS_Description', '转移关系标识。关联到core.Base表。', 'Schema', core, 'table', IDTransfer, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心标识。关联到core.DataCenter表。', 'Schema', core, 'table', IDTransfer, 'column', CenterId
;

EXEC sp_addextendedproperty 'MS_Description', '原始的标识。', 'Schema', core, 'table', IDTransfer, 'column', SourceId
;

EXEC sp_addextendedproperty 'MS_Description', '在当前数据中心中的标识。关联到core.Base表。', 'Schema', core, 'table', IDTransfer, 'column', InternalId
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心信息表。', 'Schema', core, 'table', DataCeter
;
EXEC sp_addextendedproperty 'MS_Description', '数据中心在本机中的标识。关联到core.Base表。', 'Schema', core, 'table', DataCeter, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心英文代码。', 'Schema', core, 'table', DataCeter, 'column', Code
;

EXEC sp_addextendedproperty 'MS_Description', '是否为总数据中心。1/0。只能有一个总数据中心。', 'Schema', core, 'table', DataCeter, 'column', IsGlobal
;

EXEC sp_addextendedproperty 'MS_Description', '总数据中心的MAC地址。', 'Schema', core, 'table', DataCeter, 'column', Mac
;

EXEC sp_addextendedproperty 'MS_Description', '应用注册信息。', 'Schema', sso, 'table', Application
;
EXEC sp_addextendedproperty 'MS_Description', '应用信息标识。关联到core.Base表。', 'Schema', sso, 'table', Application, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置标识。关联到sso.Configuration表。', 'Schema', sso, 'table', Application, 'column', ConfigId
;

EXEC sp_addextendedproperty 'MS_Description', '应用名称。', 'Schema', sso, 'table', Application, 'column', AppName
;

EXEC sp_addextendedproperty 'MS_Description', '是否为测试版的应用。1/0。', 'Schema', sso, 'table', Application, 'column', IsBeta
;

EXEC sp_addextendedproperty 'MS_Description', '用于获取服务信息的邮件地址。', 'Schema', sso, 'table', Application, 'column', EmailOfService
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置信息。', 'Schema', sso, 'table', Configuration
;
EXEC sp_addextendedproperty 'MS_Description', '配置信息标识。关联到core.Base表。', 'Schema', sso, 'table', Configuration, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '配置标识名称。', 'Schema', sso, 'table', Configuration, 'column', ConfigName
;

EXEC sp_addextendedproperty 'MS_Description', '是否启用开放API访问。1/0。', 'Schema', sso, 'table', Configuration, 'column', StartOpenAPI
;

EXEC sp_addextendedproperty 'MS_Description', '是否为私有配置。1/0。', 'Schema', sso, 'table', Configuration, 'column', IsPrivate
;

EXEC sp_addextendedproperty 'MS_Description', '是否可以继承。1/0。', 'Schema', sso, 'table', Configuration, 'column', CanInherit
;

EXEC sp_addextendedproperty 'MS_Description', '继承的配置标识。', 'Schema', sso, 'table', Configuration, 'column', BaseId
;

EXEC sp_addextendedproperty 'MS_Description', '用于保存令牌数据的键名称。', 'Schema', sso, 'table', Configuration, 'column', TokenMark
;

EXEC sp_addextendedproperty 'MS_Description', '令牌超时分钟数。', 'Schema', sso, 'table', Configuration, 'column', TokenExpiredMins
;

EXEC sp_addextendedproperty 'MS_Description', '退出后，下次必须重新登录。', 'Schema', sso, 'table', Configuration, 'column', SsoRequired
;

EXEC sp_addextendedproperty 'MS_Description', '是否显示注册链接。', 'Schema', sso, 'table', Configuration, 'column', ShowRegisterLink
;

EXEC sp_addextendedproperty 'MS_Description', '注册链接地址。', 'Schema', sso, 'table', Configuration, 'column', RegisterLinkUrl
;

EXEC sp_addextendedproperty 'MS_Description', '默认的语言LCID。', 'Schema', sso, 'table', Configuration, 'column', DefaultLanguage
;

EXEC sp_addextendedproperty 'MS_Description', '对象基本属性信息表。', 'Schema', core, 'table', Base
;
EXEC sp_addextendedproperty 'MS_Description', '对象唯一标识。', 'Schema', core, 'table', Base, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '对象的开放标识。', 'Schema', core, 'table', Base, 'column', PublicId
;

EXEC sp_addextendedproperty 'MS_Description', '是否可用。1/0。', 'Schema', core, 'table', Base, 'column', Enabled
;

EXEC sp_addextendedproperty 'MS_Description', '是否已经被逻辑移除。1/0。', 'Schema', core, 'table', Base, 'column', IsRemoved
;

EXEC sp_addextendedproperty 'MS_Description', '是否可见。1/0。', 'Schema', core, 'table', Base, 'column', Visible
;

EXEC sp_addextendedproperty 'MS_Description', '是否为默认的对象。1/0。', 'Schema', core, 'table', Base, 'column', IsDefault
;

EXEC sp_addextendedproperty 'MS_Description', '是否已经被激活。', 'Schema', core, 'table', Base, 'column', Actived
;

EXEC sp_addextendedproperty 'MS_Description', '排序标记。', 'Schema', core, 'table', Base, 'column', SortId
;

EXEC sp_addextendedproperty 'MS_Description', '版本号。', 'Schema', core, 'table', Base, 'column', Version
;

EXEC sp_addextendedproperty 'MS_Description', '是否被锁定。1/0。', 'Schema', core, 'table', Base, 'column', IsLocked
;

EXEC sp_addextendedproperty 'MS_Description', '是否被冻结。', 'Schema', core, 'table', Base, 'column', IsFrozen
;

EXEC sp_addextendedproperty 'MS_Description', '对象的创建时间。', 'Schema', core, 'table', Base, 'column', CreatedTime
;

EXEC sp_addextendedproperty 'MS_Description', '最后一次被修改的时间。', 'Schema', core, 'table', Base, 'column', LastModifiedTime
;

EXEC sp_addextendedproperty 'MS_Description', '对象信息被修改的次数。', 'Schema', core, 'table', Base, 'column', ModifiedTimes
;

EXEC sp_addextendedproperty 'MS_Description', '扩展的属性。', 'Schema', core, 'table', Base, 'column', ExtendedAttributes
;

EXEC sp_addextendedproperty 'MS_Description', '为了保证兼容性的扩展属性。', 'Schema', core, 'table', Base, 'column', CompatibleExtendedAttributes
;

EXEC sp_addextendedproperty 'MS_Description', '描述信息。', 'Schema', core, 'table', Base, 'column', Description
;

EXEC sp_addextendedproperty 'MS_Description', '备注信息。', 'Schema', core, 'table', Base, 'column', Comments
;
