--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期四, 25 九月, 2014 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 


--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Token_Progress') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Token DROP CONSTRAINT FK_Token_Progress
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Token_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Token DROP CONSTRAINT FK_Token_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Progress_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Progress DROP CONSTRAINT FK_Progress_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Progress_Process') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Progress DROP CONSTRAINT FK_Progress_Process
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Process_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Process DROP CONSTRAINT FK_Process_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Process_Application') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Process DROP CONSTRAINT FK_Process_Application
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_UserAccountMessage_Message') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.UserAccountMessage DROP CONSTRAINT FK_UserAccountMessage_Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_UserAccountMessage_UserAccount') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.UserAccountMessage DROP CONSTRAINT FK_UserAccountMessage_UserAccount
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_UserAccount_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.UserAccount DROP CONSTRAINT FK_UserAccount_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_UserAccount_UserProperty') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.UserAccount DROP CONSTRAINT FK_UserAccount_UserProperty
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_UserPropertyMessage_Message') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.UserPropertyMessage DROP CONSTRAINT FK_UserPropertyMessage_Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_UserPropertyMessage_UserProperty') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.UserPropertyMessage DROP CONSTRAINT FK_UserPropertyMessage_UserProperty
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_UserProperty_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.UserProperty DROP CONSTRAINT FK_UserProperty_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_CertificateMessage_Certificate') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.CertificateMessage DROP CONSTRAINT FK_CertificateMessage_Certificate
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_CertificateMessage_Message') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.CertificateMessage DROP CONSTRAINT FK_CertificateMessage_Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_Certificate_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.Certificate DROP CONSTRAINT FK_Certificate_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeWorkflow_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeWorkflow DROP CONSTRAINT FK_SubscribeWorkflow_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeWorkflow_Message') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeWorkflow DROP CONSTRAINT FK_SubscribeWorkflow_Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeWorkflow_SubscribeChannel') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeWorkflow DROP CONSTRAINT FK_SubscribeWorkflow_SubscribeChannel
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeChannel_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeChannel DROP CONSTRAINT FK_SubscribeChannel_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeChannel_SubscribeServer') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeChannel DROP CONSTRAINT FK_SubscribeChannel_SubscribeServer
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeChannel_PublishEvent') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeChannel DROP CONSTRAINT FK_SubscribeChannel_PublishEvent
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeServer_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeServer DROP CONSTRAINT FK_SubscribeServer_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SubscribeServer_DataCeter') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SubscribeServer DROP CONSTRAINT FK_SubscribeServer_DataCeter
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SsoConfiguration_Configuration') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SsoConfigurationMessage DROP CONSTRAINT FK_SsoConfiguration_Configuration
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_SsoConfigurationMessage_Message') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.SsoConfigurationMessage DROP CONSTRAINT FK_SsoConfigurationMessage_Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Message_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Message DROP CONSTRAINT FK_Message_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Message_Event') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Message DROP CONSTRAINT FK_Message_Event
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_PublishEvent_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.PublishEvent DROP CONSTRAINT FK_PublishEvent_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Event_PublishEvent') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Event DROP CONSTRAINT FK_Event_PublishEvent
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.FK_Event_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE dist.Event DROP CONSTRAINT FK_Event_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_IDTransfer_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.IDTransfer DROP CONSTRAINT FK_IDTransfer_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_IDTransfer_DataCeter') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.IDTransfer DROP CONSTRAINT FK_IDTransfer_DataCeter
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_IDTransfer_Base_02') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.IDTransfer DROP CONSTRAINT FK_IDTransfer_Base_02
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.FK_DataCeter_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE core.DataCeter DROP CONSTRAINT FK_DataCeter_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Application_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Application DROP CONSTRAINT FK_Application_Base
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Application_Configuration') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Application DROP CONSTRAINT FK_Application_Configuration
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.FK_Configuration_Base') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE sso.Configuration DROP CONSTRAINT FK_Configuration_Base
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Token') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Token
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Progress') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Progress
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Process') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Process
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.UserAccountMessage') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.UserAccountMessage
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.UserAccount') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.UserAccount
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.UserPropertyMessage') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.UserPropertyMessage
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.UserProperty') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.UserProperty
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.CertificateMessage') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.CertificateMessage
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.Certificate') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.Certificate
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.SubscribeWorkflow') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.SubscribeWorkflow
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.SubscribeChannel') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.SubscribeChannel
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.SubscribeServer') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.SubscribeServer
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.SsoConfigurationMessage') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.SsoConfigurationMessage
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.Message') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.Message
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.PublishEvent') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.PublishEvent
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('dist.Event') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE dist.Event
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.IDTransfer') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.IDTransfer
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.DataCeter') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.DataCeter
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Application') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Application
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('sso.Configuration') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE sso.Configuration
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('core.Base') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.Base
;


--  Create Tables 
CREATE TABLE sso.Token ( 
	Id uniqueidentifier NOT NULL,    --  令牌标记。关联到core.Base表。 
	ProgressId uniqueidentifier NOT NULL,    --  SSO登录进度标识。关联到sso.Progress表。 
	TokenData varbinary(max) NOT NULL,    --  令牌字节数据。 
	TokenHexStr varchar(max) NOT NULL    --  令牌的16进制字符串表达式。 
)
;

CREATE TABLE sso.Progress ( 
	Id uniqueidentifier NOT NULL,    --  登录进度标识。关联到core.Base表。 
	ProcessId uniqueidentifier NOT NULL,    --  登录进程标识。关联到sso.Process表。 
	Success bit DEFAULT 1 NOT NULL    --  是否成功。1/0。 
)
;

CREATE TABLE sso.Process ( 
	Id uniqueidentifier NOT NULL,    --  登录进程标识。关联到core.Base表。 
	AppId uniqueidentifier NOT NULL,    --  请求SSO登录验证的应用标识。关联到sso.Application表。 
	IsWeb bit DEFAULT 1 NOT NULL,    --  是否为WEB应用。 
	RawUrl varchar(max) DEFAULT NULL,    --  请求登录的原始URL。 
	ClientIP varchar(64) DEFAULT NULL,    --  请求SSO的客户端IP地址。 
	HostName varchar(256) DEFAULT NULL    --  请求SSO的客户端主机名称。 
)
;

CREATE TABLE dist.UserAccountMessage ( 
	MessageId uniqueidentifier NOT NULL,    --  账户消息标识。关联到dist.Message表。 
	AccountId uniqueidentifier NOT NULL,    --  账户标识。关联到sso.UserAccount表。 
	UserName varbinary(max) NOT NULL,    --  用户名字节数据（加密的） 
	Password varchar(max) DEFAULT NULL,    --  账户口令（C# MD5加密） 
	IsExternal bit DEFAULT 0 NOT NULL    --  是否为外部账户。1/0。 
)
;

CREATE TABLE sso.UserAccount ( 
	Id uniqueidentifier NOT NULL,    --  账户标识。关联到core.Base表。 
	PropertyId uniqueidentifier DEFAULT NULL,    --  关联的用户基本属性标识。关联到core.UserProperty表。 
	UserName varbinary(max) NOT NULL,    --  用户名字节数据（加密的） 
	Password varchar(max) DEFAULT NULL,    --  账户口令（C# MD5加密） 
	IsExternal bit DEFAULT 0 NOT NULL    --  是否为外部账户。1/0。 
)
;

CREATE TABLE dist.UserPropertyMessage ( 
	MessageId uniqueidentifier NOT NULL,    --  用户基本属性消息标识。关联到dist.Message表。 
	Id uniqueidentifier NOT NULL,    --  用户基本属性标识。关联到core.UserProperty表。 
	FirstName nvarchar(32) NOT NULL,    --  用户的名字。 
	LastName nvarchar(32) NOT NULL,    --  用户的姓氏。 
	FullName nvarchar(64) NOT NULL,    --  用户的完整姓名。 
	Gender char(1) DEFAULT 'M' NOT NULL,    --  性别。M：男；W：女；U：未知的。 
	BirthDate datetime DEFAULT NULL,    --  出生日期。 
	Age int DEFAULT NULL,    --  年龄。 
	CertificateId uniqueidentifier DEFAULT NULL,    --  证件类型标识。关联到core.Certificate表。 
	CertificateNO varbinary(max) DEFAULT NULL,    --  证件编号数据（加密的）。 
	OfficePhoneNO varbinary(max) DEFAULT NULL,    --  办公电话号码数据（加密的）。 
	MobileNO varbinary(max) DEFAULT NULL,    --  移动电话号码数据（加密的）。 
	Email varbinary(max) DEFAULT NULL    --  电子邮件数据（加密的）。 
)
;

CREATE TABLE core.UserProperty ( 
	Id uniqueidentifier NOT NULL,    --  用户基本属性标识。关联到core.Base表。 
	FirstName nvarchar(32) NOT NULL,    --  用户的名字。 
	LastName nvarchar(32) NOT NULL,    --  用户的姓氏。 
	FullName nvarchar(64) NOT NULL,    --  用户的完整姓名。 
	Gender char(1) DEFAULT 'M' NOT NULL,    --  性别。M：男；W：女；U：未知的。 
	BirthDate datetime DEFAULT NULL,    --  出生日期。 
	Age int DEFAULT NULL,    --  年龄。 
	CertificateId uniqueidentifier DEFAULT NULL,    --  证件类型标识。关联到core.Certificate表。 
	CertificateNO varbinary(max) DEFAULT NULL,    --  证件编号数据（加密的）。 
	OfficePhoneNO varbinary(max) DEFAULT NULL,    --  办公电话号码数据（加密的）。 
	MobileNO varbinary(max) DEFAULT NULL,    --  移动电话号码数据（加密的）。 
	Email varbinary(max) DEFAULT NULL    --  电子邮件数据（加密的）。 
)
;

CREATE TABLE dist.CertificateMessage ( 
	MessageId uniqueidentifier NOT NULL,    --  消息标识。关联到dist.Message表。 
	CertificateId uniqueidentifier NOT NULL,    --  证件类型参数标识。关联到core.Certificate表。 
	Category nvarchar(64) NOT NULL,    --  证件类型名称。 
	IsPublic bit DEFAULT 1 NOT NULL    --  是否公用。1/0。 
)
;

CREATE TABLE core.Certificate ( 
	Id uniqueidentifier NOT NULL,    --  证件类型标识。 
	Category nvarchar(64) NOT NULL,    --  证件类型名称。 
	IsPublic bit DEFAULT 1 NOT NULL    --  是否公用。1/0。 
)
;

CREATE TABLE dist.SubscribeWorkflow ( 
	Id uniqueidentifier NOT NULL,    --  工作流标识。关联到core.Base表。 
	PrevWfID uniqueidentifier DEFAULT NULL,    --  前一个工作流标识。 
	MessageId uniqueidentifier NOT NULL,    --  消息标识。关联到dist.Message表。 
	ChannelId uniqueidentifier NOT NULL,    --  预订通道标识。关联到dist.SubscribeChannel表。 
	Status int DEFAULT 1 NOT NULL    --  工作流状态。1：待发送；2：提取到队列；3：已发送；4：等待补发；5：放弃；65535：终止。 
)
;

CREATE TABLE dist.SubscribeChannel ( 
	Id uniqueidentifier NOT NULL,    --  预定通道标记。关联到core.Base表。 
	ServerId uniqueidentifier NOT NULL,    --  预订服务器标识。关联到dist.SubscribeServer表。 
	PublishMsgId uniqueidentifier NOT NULL,    --  需要预订的数据发布事件标识。关联到dist.PublishEvent表。 
	MessageQueuePath varchar(256) NOT NULL,    --  接收预订数据的MSMQ私有队列路径。 
	IsTransactional bit DEFAULT 1 NOT NULL,    --  是否为事务性的私有队列。1/0。 
	MaxReissueTimes int DEFAULT 5 NOT NULL,    --  最大补发次数。1/0。 
	Deadletter bit DEFAULT 1 NOT NULL,    --  发送失败后，是否允许加入死信。 
	ReceiptRequired bit DEFAULT 1 NOT NULL,    --  是否需要各种状态回执。1/0。 
	TimeoutMins int DEFAULT 10 NOT NULL    --  预订数据发送超时分钟数。超过则直接加入死信或者放弃。 
)
;

CREATE TABLE dist.SubscribeServer ( 
	Id uniqueidentifier NOT NULL,    --  预订服务器唯一标识。关联到core.Base表。 
	CenterId uniqueidentifier NOT NULL,    --  所属的分数据中心标识。关联到core.DataCenter表。 
	MachineName varchar(64) NOT NULL,    --  服务器机器名。 
	IPv4 varchar(15) NOT NULL,    --  v4版本的IP地址。 
	IPv6 varchar(128) DEFAULT NULL    --  v6版本的IP地址。 
)
;

CREATE TABLE dist.SsoConfigurationMessage ( 
	MessageId uniqueidentifier NOT NULL,    --  分发的消息标识。关联到dist.Message表。 
	ConfigId uniqueidentifier NOT NULL,    --  SSO配置标识。关联到sso.Configuration表。 
	ConfigName nvarchar(256) NOT NULL,    --  配置名称。 
	StartOpenAPI bit NOT NULL,    --  是否启用开放式API。 
	CanInherit bit DEFAULT 1 NOT NULL,    --  是否可以继承。 
	BaseId uniqueidentifier,    --  继承自的配置标识。 
	TokenMark varchar(32) NOT NULL,    --  令牌标记名称。 
	TokenExpiredMins int DEFAULT 30 NOT NULL,    --  令牌失效分钟数。 
	SsoRequired bit NOT NULL,    --  SSO验证是否是必须的。 
	ShowRegisterLink bit NOT NULL,    --  是否显示注册链接。 
	RegisterLinkUrl varchar(1024),    --  注册链接地址。 
	DefaultLanguage int DEFAULT 2052 NOT NULL    --  默认语言。 
)
;

CREATE TABLE dist.Message ( 
	Id uniqueidentifier NOT NULL,    --  消息标识。关联到core.Base表。 
	EventId uniqueidentifier NOT NULL,    --  关联的事件表示。关联到dist.Event表。 
	Completed bit DEFAULT 1 NOT NULL,    --  是否准备完毕。1/0。 
	Action char(1) DEFAULT 'C' NOT NULL    --  消息的动作。'C':创建;‘U'：更新；'R'：逻辑移除；'D'：物理移除。 
)
;

CREATE TABLE dist.PublishEvent ( 
	Id uniqueidentifier NOT NULL,    --  分发事件类型唯一标识。关联到core.Base表。 
	CmdTemplate varchar(max) NOT NULL    --  SQL命令模板。 
)
;

CREATE TABLE dist.Event ( 
	Id uniqueidentifier NOT NULL,    --  分发事件标识。 
	TypeId uniqueidentifier NOT NULL,    --  分发事件类型标识。关联到dist.PublishEvent表。 
	Cmd varchar(max) NOT NULL    --  获取分发数据的SQL命令文本。 
)
;

CREATE TABLE core.IDTransfer ( 
	Id uniqueidentifier NOT NULL,    --  转移关系标识。关联到core.Base表。 
	CenterId uniqueidentifier NOT NULL,    --  数据中心标识。关联到core.DataCenter表。 
	SourceId uniqueidentifier NOT NULL,    --  原始的标识。 
	InternalId uniqueidentifier NOT NULL    --  在当前数据中心中的标识。关联到core.Base表。 
)
;

CREATE TABLE core.DataCeter ( 
	Id uniqueidentifier NOT NULL,    --  数据中心在本机中的标识。关联到core.Base表。 
	Code varchar(64) NOT NULL,    --  数据中心英文代码。 
	IsGlobal bit DEFAULT 0 NOT NULL,    --  是否为总数据中心。1/0。只能有一个总数据中心。 
	Mac varchar(128) NOT NULL    --  总数据中心的MAC地址。 
)
;

CREATE TABLE sso.Application ( 
	Id uniqueidentifier NOT NULL,    --  应用信息标识。关联到core.Base表。 
	ConfigId uniqueidentifier NOT NULL,    --  SSO配置标识。关联到sso.Configuration表。 
	AppName nvarchar(128) NOT NULL,    --  应用名称。 
	IsBeta bit DEFAULT 0 NOT NULL,    --  是否为测试版的应用。1/0。 
	EmailOfService varchar(512) NOT NULL    --  用于获取服务信息的邮件地址。 
)
;

CREATE TABLE sso.Configuration ( 
	Id uniqueidentifier NOT NULL,    --  配置信息标识。关联到core.Base表。 
	ConfigName nvarchar(256) NOT NULL,    --  配置标识名称。 
	StartOpenAPI bit DEFAULT 1 NOT NULL,    --  是否启用开放API访问。1/0。 
	IsPrivate bit DEFAULT 0 NOT NULL,    --  是否为私有配置。1/0。 
	CanInherit bit DEFAULT 1 NOT NULL,    --  是否可以继承。1/0。 
	BaseId uniqueidentifier DEFAULT NULL,    --  继承的配置标识。 
	TokenMark varchar(32) NOT NULL,    --  用于保存令牌数据的键名称。 
	TokenExpiredMins int DEFAULT 30 NOT NULL,    --  令牌超时分钟数。 
	SsoRequired bit DEFAULT 1 NOT NULL,    --  退出后，下次必须重新登录。 
	ShowRegisterLink bit DEFAULT 1 NOT NULL,    --  是否显示注册链接。 
	RegisterLinkUrl varchar(1024) DEFAULT NULL,    --  注册链接地址。 
	DefaultLanguage int DEFAULT 2052 NOT NULL    --  默认的语言LCID。 
)
;

CREATE TABLE core.Base ( 
	Id uniqueidentifier DEFAULT Newid() NOT NULL,    --  对象唯一标识。 
	PublicId varchar(256) NOT NULL,    --  对象的开放标识。 
	Enabled bit DEFAULT 1 NOT NULL,    --  是否可用。1/0。 
	IsRemoved bit DEFAULT 0 NOT NULL,    --  是否已经被逻辑移除。1/0。 
	Visible bit DEFAULT 1 NOT NULL,    --  是否可见。1/0。 
	IsDefault bit DEFAULT 1 NOT NULL,    --  是否为默认的对象。1/0。 
	Actived bit DEFAULT 1 NOT NULL,    --  是否已经被激活。 
	SortId int DEFAULT 0 NOT NULL,    --  排序标记。 
	Version decimal(19,2) DEFAULT 1.00 NOT NULL,    --  版本号。 
	IsLocked bit DEFAULT 0 NOT NULL,    --  是否被锁定。1/0。 
	IsFrozen bit DEFAULT 0 NOT NULL,    --  是否被冻结。 
	CreatedTime datetime DEFAULT Getdate() NOT NULL,    --  对象的创建时间。 
	LastModifiedTime datetime DEFAULT Getdate() NOT NULL,    --  最后一次被修改的时间。 
	ModifiedTimes int DEFAULT 0 NOT NULL,    --  对象信息被修改的次数。 
	ExtendedAttributes xml DEFAULT NULL,    --  扩展的属性。 
	CompatibleExtendedAttributes nvarchar(max) DEFAULT NULL,    --  为了保证兼容性的扩展属性。 
	Description nvarchar(max) DEFAULT NULL,    --  描述信息。 
	Comments nvarchar(max) DEFAULT NULL    --  备注信息。 
)
;


--  Create Indexes 
ALTER TABLE sso.Token
	ADD CONSTRAINT UQ_Token_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Token_Progress
	ON sso.Token (ProgressId ASC)
;

CREATE INDEX IXFK_Token_Base
	ON sso.Token (Id ASC)
;

ALTER TABLE sso.Progress
	ADD CONSTRAINT UQ_Progress_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Progress_Base
	ON sso.Progress (Id ASC)
;

CREATE INDEX IXFK_Progress_Process
	ON sso.Progress (ProcessId ASC)
;

ALTER TABLE sso.Process
	ADD CONSTRAINT UQ_Process_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Process_Base
	ON sso.Process (Id ASC)
;

CREATE INDEX IXFK_Process_Application
	ON sso.Process (AppId ASC)
;

ALTER TABLE dist.UserAccountMessage
	ADD CONSTRAINT UQ_UserAccountMessage_MessageId UNIQUE (MessageId)
;

CREATE INDEX IXFK_UserAccountMessage_Message
	ON dist.UserAccountMessage (MessageId ASC)
;

CREATE INDEX IXFK_UserAccountMessage_UserAccount
	ON dist.UserAccountMessage (AccountId ASC)
;

ALTER TABLE sso.UserAccount
	ADD CONSTRAINT UQ_UserAccount_Id UNIQUE (Id)
;

CREATE INDEX IXFK_UserAccount_Base
	ON sso.UserAccount (Id ASC)
;

CREATE INDEX IXFK_UserAccount_UserProperty
	ON sso.UserAccount (PropertyId ASC)
;

ALTER TABLE dist.UserPropertyMessage
	ADD CONSTRAINT UQ_UserPropertyMessage_MessageId UNIQUE (MessageId)
;

ALTER TABLE dist.UserPropertyMessage
	ADD CONSTRAINT UQ_UserPropertyMessage_Id UNIQUE (Id)
;

CREATE INDEX IXFK_UserPropertyMessage_Message
	ON dist.UserPropertyMessage (MessageId ASC)
;

CREATE INDEX IXFK_UserPropertyMessage_UserProperty
	ON dist.UserPropertyMessage (Id ASC)
;

ALTER TABLE core.UserProperty
	ADD CONSTRAINT UQ_UserProperty_Id UNIQUE (Id)
;

CREATE INDEX IXFK_UserProperty_Base
	ON core.UserProperty (Id ASC)
;

ALTER TABLE dist.CertificateMessage
	ADD CONSTRAINT UQ_CertificateMessage_MessageId UNIQUE (MessageId)
;

CREATE INDEX IXFK_CertificateMessage_Certificate
	ON dist.CertificateMessage (CertificateId ASC)
;

CREATE INDEX IXFK_CertificateMessage_Message
	ON dist.CertificateMessage (MessageId ASC)
;

ALTER TABLE core.Certificate
	ADD CONSTRAINT UQ_Certificate_Id UNIQUE (Id)
;

ALTER TABLE core.Certificate
	ADD CONSTRAINT UQ_Certificate_Category UNIQUE (Category)
;

CREATE INDEX IXFK_Certificate_Base
	ON core.Certificate (Id ASC)
;

ALTER TABLE dist.SubscribeWorkflow
	ADD CONSTRAINT UQ_SubscribeWorkflow_Id UNIQUE (Id)
;

CREATE INDEX IXFK_SubscribeWorkflow_Base
	ON dist.SubscribeWorkflow (Id ASC)
;

CREATE INDEX IXFK_SubscribeWorkflow_Message
	ON dist.SubscribeWorkflow (MessageId ASC)
;

CREATE INDEX IXFK_SubscribeWorkflow_SubscribeChannel
	ON dist.SubscribeWorkflow (ChannelId ASC)
;

ALTER TABLE dist.SubscribeChannel
	ADD CONSTRAINT UQ_SubscribeChannel_Id UNIQUE (Id)
;

CREATE INDEX IXFK_SubscribeChannel_Base
	ON dist.SubscribeChannel (Id ASC)
;

CREATE INDEX IXFK_SubscribeChannel_SubscribeServer
	ON dist.SubscribeChannel (ServerId ASC)
;

CREATE INDEX IXFK_SubscribeChannel_PublishEvent
	ON dist.SubscribeChannel (PublishMsgId ASC)
;

ALTER TABLE dist.SubscribeServer
	ADD CONSTRAINT UQ_SubscribeServer_MachineName UNIQUE (MachineName)
;

ALTER TABLE dist.SubscribeServer
	ADD CONSTRAINT UQ_SubscribeServer_IPv4 UNIQUE (IPv4)
;

CREATE INDEX IXFK_SubscribeServer_Base
	ON dist.SubscribeServer (Id ASC)
;

CREATE INDEX IXFK_SubscribeServer_DataCeter
	ON dist.SubscribeServer (CenterId ASC)
;

ALTER TABLE dist.SubscribeServer
	ADD CONSTRAINT UQ_SubscribeServer_Id UNIQUE (Id)
;

CREATE INDEX IXFK_SsoConfiguration_Configuration
	ON dist.SsoConfigurationMessage (ConfigId ASC)
;

CREATE INDEX IXFK_SsoConfigurationMessage_Message
	ON dist.SsoConfigurationMessage (MessageId ASC)
;

ALTER TABLE dist.Message
	ADD CONSTRAINT UQ_Message_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Message_Base
	ON dist.Message (Id ASC)
;

CREATE INDEX IXFK_Message_Event
	ON dist.Message (EventId ASC)
;

ALTER TABLE dist.PublishEvent
	ADD CONSTRAINT UQ_PublishEvent_Id UNIQUE (Id)
;

CREATE INDEX IXFK_PublishEvent_Base
	ON dist.PublishEvent (Id ASC)
;

CREATE INDEX IXFK_Event_PublishEvent
	ON dist.Event (TypeId ASC)
;

ALTER TABLE dist.Event
	ADD CONSTRAINT UQ_Event_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Event_Base
	ON dist.Event (Id ASC)
;

ALTER TABLE core.IDTransfer
	ADD CONSTRAINT UQ_IDTransfer_Id UNIQUE (Id)
;

CREATE INDEX IXFK_IDTransfer_Base
	ON core.IDTransfer (Id ASC)
;

CREATE INDEX IXFK_IDTransfer_DataCeter
	ON core.IDTransfer (CenterId ASC)
;

CREATE INDEX IXFK_IDTransfer_Base_02
	ON core.IDTransfer (InternalId ASC)
;

ALTER TABLE core.DataCeter
	ADD CONSTRAINT UQ_DataCeter_Code UNIQUE (Code)
;

ALTER TABLE core.DataCeter
	ADD CONSTRAINT UQ_DataCeter_Id UNIQUE (Id)
;

CREATE INDEX IXFK_DataCeter_Base
	ON core.DataCeter (Id ASC)
;

ALTER TABLE core.DataCeter
	ADD CONSTRAINT UQ_DataCeter_Mac UNIQUE (Mac)
;

ALTER TABLE sso.Application
	ADD CONSTRAINT UQ_Application_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Application_Base
	ON sso.Application (Id ASC)
;

CREATE INDEX IXFK_Application_Configuration
	ON sso.Application (ConfigId ASC)
;

ALTER TABLE sso.Application
	ADD CONSTRAINT UQ_Application_AppName UNIQUE (AppName)
;

ALTER TABLE sso.Configuration
	ADD CONSTRAINT UQ_Configuration_Id UNIQUE (Id)
;

CREATE INDEX IXFK_Configuration_Base
	ON sso.Configuration (Id ASC)
;

ALTER TABLE sso.Configuration
	ADD CONSTRAINT UQ_Configuration_ConfigMark UNIQUE (ConfigName)
;

ALTER TABLE core.Base
	ADD CONSTRAINT UQ_Base_Id UNIQUE (Id)
;

--  Create Primary Key Constraints 
ALTER TABLE sso.Token ADD CONSTRAINT PK_Token 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE sso.Progress ADD CONSTRAINT PK_Progress 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE sso.Process ADD CONSTRAINT PK_Process 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.UserAccountMessage ADD CONSTRAINT PK_UserAccountMessage 
	PRIMARY KEY CLUSTERED (MessageId)
;

ALTER TABLE sso.UserAccount ADD CONSTRAINT PK_UserAccount 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.UserPropertyMessage ADD CONSTRAINT PK_UserPropertyMessage 
	PRIMARY KEY CLUSTERED (MessageId)
;

ALTER TABLE core.UserProperty ADD CONSTRAINT PK_UserProperty 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.CertificateMessage ADD CONSTRAINT PK_CertificateMessage 
	PRIMARY KEY CLUSTERED (MessageId)
;

ALTER TABLE core.Certificate ADD CONSTRAINT PK_Certificate 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.SubscribeWorkflow ADD CONSTRAINT PK_SubscribeWorkflow 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.SubscribeChannel ADD CONSTRAINT PK_SubscribeChannel 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.SubscribeServer ADD CONSTRAINT PK_SubscribeServer 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.SsoConfigurationMessage ADD CONSTRAINT PK_SsoConfiguration 
	PRIMARY KEY CLUSTERED (MessageId)
;

ALTER TABLE dist.Message ADD CONSTRAINT PK_Message 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.PublishEvent ADD CONSTRAINT PK_PublishEvent 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE dist.Event ADD CONSTRAINT PK_Event 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT PK_IDTransfer 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE core.DataCeter ADD CONSTRAINT PK_DataCeter 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE sso.Application ADD CONSTRAINT PK_Application 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE sso.Configuration ADD CONSTRAINT PK_Configuration 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE core.Base ADD CONSTRAINT PK_Base 
	PRIMARY KEY CLUSTERED (Id)
;



--  Create Foreign Key Constraints 
ALTER TABLE sso.Token ADD CONSTRAINT FK_Token_Progress 
	FOREIGN KEY (ProgressId) REFERENCES sso.Progress (Id)
;

ALTER TABLE sso.Token ADD CONSTRAINT FK_Token_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Progress ADD CONSTRAINT FK_Progress_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Progress ADD CONSTRAINT FK_Progress_Process 
	FOREIGN KEY (ProcessId) REFERENCES sso.Process (Id)
;

ALTER TABLE sso.Process ADD CONSTRAINT FK_Process_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Process ADD CONSTRAINT FK_Process_Application 
	FOREIGN KEY (AppId) REFERENCES sso.Application (Id)
;

ALTER TABLE dist.UserAccountMessage ADD CONSTRAINT FK_UserAccountMessage_Message 
	FOREIGN KEY (MessageId) REFERENCES dist.Message (Id)
;

ALTER TABLE dist.UserAccountMessage ADD CONSTRAINT FK_UserAccountMessage_UserAccount 
	FOREIGN KEY (AccountId) REFERENCES sso.UserAccount (Id)
;

ALTER TABLE sso.UserAccount ADD CONSTRAINT FK_UserAccount_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.UserAccount ADD CONSTRAINT FK_UserAccount_UserProperty 
	FOREIGN KEY (PropertyId) REFERENCES core.UserProperty (Id)
;

ALTER TABLE dist.UserPropertyMessage ADD CONSTRAINT FK_UserPropertyMessage_Message 
	FOREIGN KEY (MessageId) REFERENCES dist.Message (Id)
;

ALTER TABLE dist.UserPropertyMessage ADD CONSTRAINT FK_UserPropertyMessage_UserProperty 
	FOREIGN KEY (Id) REFERENCES core.UserProperty (Id)
;

ALTER TABLE core.UserProperty ADD CONSTRAINT FK_UserProperty_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.CertificateMessage ADD CONSTRAINT FK_CertificateMessage_Certificate 
	FOREIGN KEY (CertificateId) REFERENCES core.Certificate (Id)
;

ALTER TABLE dist.CertificateMessage ADD CONSTRAINT FK_CertificateMessage_Message 
	FOREIGN KEY (MessageId) REFERENCES dist.Message (Id)
;

ALTER TABLE core.Certificate ADD CONSTRAINT FK_Certificate_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.SubscribeWorkflow ADD CONSTRAINT FK_SubscribeWorkflow_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.SubscribeWorkflow ADD CONSTRAINT FK_SubscribeWorkflow_Message 
	FOREIGN KEY (MessageId) REFERENCES dist.Message (Id)
;

ALTER TABLE dist.SubscribeWorkflow ADD CONSTRAINT FK_SubscribeWorkflow_SubscribeChannel 
	FOREIGN KEY (ChannelId) REFERENCES dist.SubscribeChannel (Id)
;

ALTER TABLE dist.SubscribeChannel ADD CONSTRAINT FK_SubscribeChannel_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.SubscribeChannel ADD CONSTRAINT FK_SubscribeChannel_SubscribeServer 
	FOREIGN KEY (ServerId) REFERENCES dist.SubscribeServer (Id)
;

ALTER TABLE dist.SubscribeChannel ADD CONSTRAINT FK_SubscribeChannel_PublishEvent 
	FOREIGN KEY (PublishMsgId) REFERENCES dist.PublishEvent (Id)
;

ALTER TABLE dist.SubscribeServer ADD CONSTRAINT FK_SubscribeServer_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.SubscribeServer ADD CONSTRAINT FK_SubscribeServer_DataCeter 
	FOREIGN KEY (CenterId) REFERENCES core.DataCeter (Id)
;

ALTER TABLE dist.SsoConfigurationMessage ADD CONSTRAINT FK_SsoConfiguration_Configuration 
	FOREIGN KEY (ConfigId) REFERENCES sso.Configuration (Id)
;

ALTER TABLE dist.SsoConfigurationMessage ADD CONSTRAINT FK_SsoConfigurationMessage_Message 
	FOREIGN KEY (MessageId) REFERENCES dist.Message (Id)
;

ALTER TABLE dist.Message ADD CONSTRAINT FK_Message_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.Message ADD CONSTRAINT FK_Message_Event 
	FOREIGN KEY (EventId) REFERENCES dist.Event (Id)
;

ALTER TABLE dist.PublishEvent ADD CONSTRAINT FK_PublishEvent_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE dist.Event ADD CONSTRAINT FK_Event_PublishEvent 
	FOREIGN KEY (TypeId) REFERENCES dist.PublishEvent (Id)
;

ALTER TABLE dist.Event ADD CONSTRAINT FK_Event_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT FK_IDTransfer_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT FK_IDTransfer_DataCeter 
	FOREIGN KEY (CenterId) REFERENCES core.DataCeter (Id)
;

ALTER TABLE core.IDTransfer ADD CONSTRAINT FK_IDTransfer_Base_02 
	FOREIGN KEY (InternalId) REFERENCES core.Base (Id)
;

ALTER TABLE core.DataCeter ADD CONSTRAINT FK_DataCeter_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Application ADD CONSTRAINT FK_Application_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;

ALTER TABLE sso.Application ADD CONSTRAINT FK_Application_Configuration 
	FOREIGN KEY (ConfigId) REFERENCES sso.Configuration (Id)
;

ALTER TABLE sso.Configuration ADD CONSTRAINT FK_Configuration_Base 
	FOREIGN KEY (Id) REFERENCES core.Base (Id)
;









EXEC sp_addextendedproperty 'MS_Description', 'SSO登录验证令牌表。', 'Schema', sso, 'table', Token
;
EXEC sp_addextendedproperty 'MS_Description', '令牌标记。关联到core.Base表。', 'Schema', sso, 'table', Token, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO登录进度标识。关联到sso.Progress表。', 'Schema', sso, 'table', Token, 'column', ProgressId
;

EXEC sp_addextendedproperty 'MS_Description', '令牌字节数据。', 'Schema', sso, 'table', Token, 'column', TokenData
;

EXEC sp_addextendedproperty 'MS_Description', '令牌的16进制字符串表达式。', 'Schema', sso, 'table', Token, 'column', TokenHexStr
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO登录验证进度表。', 'Schema', sso, 'table', Progress
;
EXEC sp_addextendedproperty 'MS_Description', '登录进度标识。关联到core.Base表。', 'Schema', sso, 'table', Progress, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '登录进程标识。关联到sso.Process表。', 'Schema', sso, 'table', Progress, 'column', ProcessId
;

EXEC sp_addextendedproperty 'MS_Description', '是否成功。1/0。', 'Schema', sso, 'table', Progress, 'column', Success
;

EXEC sp_addextendedproperty 'MS_Description', '登录进程信息表。', 'Schema', sso, 'table', Process
;
EXEC sp_addextendedproperty 'MS_Description', '登录进程标识。关联到core.Base表。', 'Schema', sso, 'table', Process, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '请求SSO登录验证的应用标识。关联到sso.Application表。', 'Schema', sso, 'table', Process, 'column', AppId
;

EXEC sp_addextendedproperty 'MS_Description', '是否为WEB应用。', 'Schema', sso, 'table', Process, 'column', IsWeb
;

EXEC sp_addextendedproperty 'MS_Description', '请求登录的原始URL。', 'Schema', sso, 'table', Process, 'column', RawUrl
;

EXEC sp_addextendedproperty 'MS_Description', '请求SSO的客户端IP地址。', 'Schema', sso, 'table', Process, 'column', ClientIP
;

EXEC sp_addextendedproperty 'MS_Description', '请求SSO的客户端主机名称。', 'Schema', sso, 'table', Process, 'column', HostName
;

EXEC sp_addextendedproperty 'MS_Description', '用户账户信息消息表。', 'Schema', dist, 'table', UserAccountMessage
;
EXEC sp_addextendedproperty 'MS_Description', '账户消息标识。关联到dist.Message表。', 'Schema', dist, 'table', UserAccountMessage, 'column', MessageId
;

EXEC sp_addextendedproperty 'MS_Description', '账户标识。关联到sso.UserAccount表。', 'Schema', dist, 'table', UserAccountMessage, 'column', AccountId
;

EXEC sp_addextendedproperty 'MS_Description', '用户名字节数据（加密的）', 'Schema', dist, 'table', UserAccountMessage, 'column', UserName
;

EXEC sp_addextendedproperty 'MS_Description', '账户口令（C# MD5加密）', 'Schema', dist, 'table', UserAccountMessage, 'column', Password
;

EXEC sp_addextendedproperty 'MS_Description', '是否为外部账户。1/0。', 'Schema', dist, 'table', UserAccountMessage, 'column', IsExternal
;

EXEC sp_addextendedproperty 'MS_Description', '用户账户信息表。', 'Schema', sso, 'table', UserAccount
;
EXEC sp_addextendedproperty 'MS_Description', '账户标识。关联到core.Base表。', 'Schema', sso, 'table', UserAccount, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '关联的用户基本属性标识。关联到core.UserProperty表。', 'Schema', sso, 'table', UserAccount, 'column', PropertyId
;

EXEC sp_addextendedproperty 'MS_Description', '用户名字节数据（加密的）', 'Schema', sso, 'table', UserAccount, 'column', UserName
;

EXEC sp_addextendedproperty 'MS_Description', '账户口令（C# MD5加密）', 'Schema', sso, 'table', UserAccount, 'column', Password
;

EXEC sp_addextendedproperty 'MS_Description', '是否为外部账户。1/0。', 'Schema', sso, 'table', UserAccount, 'column', IsExternal
;

EXEC sp_addextendedproperty 'MS_Description', '用户基本属性消息表。', 'Schema', dist, 'table', UserPropertyMessage
;
EXEC sp_addextendedproperty 'MS_Description', '用户基本属性消息标识。关联到dist.Message表。', 'Schema', dist, 'table', UserPropertyMessage, 'column', MessageId
;

EXEC sp_addextendedproperty 'MS_Description', '用户基本属性标识。关联到core.UserProperty表。', 'Schema', dist, 'table', UserPropertyMessage, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '用户的名字。', 'Schema', dist, 'table', UserPropertyMessage, 'column', FirstName
;

EXEC sp_addextendedproperty 'MS_Description', '用户的姓氏。', 'Schema', dist, 'table', UserPropertyMessage, 'column', LastName
;

EXEC sp_addextendedproperty 'MS_Description', '用户的完整姓名。', 'Schema', dist, 'table', UserPropertyMessage, 'column', FullName
;

EXEC sp_addextendedproperty 'MS_Description', '性别。M：男；W：女；U：未知的。', 'Schema', dist, 'table', UserPropertyMessage, 'column', Gender
;

EXEC sp_addextendedproperty 'MS_Description', '出生日期。', 'Schema', dist, 'table', UserPropertyMessage, 'column', BirthDate
;

EXEC sp_addextendedproperty 'MS_Description', '年龄。', 'Schema', dist, 'table', UserPropertyMessage, 'column', Age
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型标识。关联到core.Certificate表。', 'Schema', dist, 'table', UserPropertyMessage, 'column', CertificateId
;

EXEC sp_addextendedproperty 'MS_Description', '证件编号数据（加密的）。', 'Schema', dist, 'table', UserPropertyMessage, 'column', CertificateNO
;

EXEC sp_addextendedproperty 'MS_Description', '办公电话号码数据（加密的）。', 'Schema', dist, 'table', UserPropertyMessage, 'column', OfficePhoneNO
;

EXEC sp_addextendedproperty 'MS_Description', '移动电话号码数据（加密的）。', 'Schema', dist, 'table', UserPropertyMessage, 'column', MobileNO
;

EXEC sp_addextendedproperty 'MS_Description', '电子邮件数据（加密的）。', 'Schema', dist, 'table', UserPropertyMessage, 'column', Email
;

EXEC sp_addextendedproperty 'MS_Description', '用户基本属性表。', 'Schema', core, 'table', UserProperty
;
EXEC sp_addextendedproperty 'MS_Description', '用户基本属性标识。关联到core.Base表。', 'Schema', core, 'table', UserProperty, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '用户的名字。', 'Schema', core, 'table', UserProperty, 'column', FirstName
;

EXEC sp_addextendedproperty 'MS_Description', '用户的姓氏。', 'Schema', core, 'table', UserProperty, 'column', LastName
;

EXEC sp_addextendedproperty 'MS_Description', '用户的完整姓名。', 'Schema', core, 'table', UserProperty, 'column', FullName
;

EXEC sp_addextendedproperty 'MS_Description', '性别。M：男；W：女；U：未知的。', 'Schema', core, 'table', UserProperty, 'column', Gender
;

EXEC sp_addextendedproperty 'MS_Description', '出生日期。', 'Schema', core, 'table', UserProperty, 'column', BirthDate
;

EXEC sp_addextendedproperty 'MS_Description', '年龄。', 'Schema', core, 'table', UserProperty, 'column', Age
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型标识。关联到core.Certificate表。', 'Schema', core, 'table', UserProperty, 'column', CertificateId
;

EXEC sp_addextendedproperty 'MS_Description', '证件编号数据（加密的）。', 'Schema', core, 'table', UserProperty, 'column', CertificateNO
;

EXEC sp_addextendedproperty 'MS_Description', '办公电话号码数据（加密的）。', 'Schema', core, 'table', UserProperty, 'column', OfficePhoneNO
;

EXEC sp_addextendedproperty 'MS_Description', '移动电话号码数据（加密的）。', 'Schema', core, 'table', UserProperty, 'column', MobileNO
;

EXEC sp_addextendedproperty 'MS_Description', '电子邮件数据（加密的）。', 'Schema', core, 'table', UserProperty, 'column', Email
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型参数消息表。', 'Schema', dist, 'table', CertificateMessage
;
EXEC sp_addextendedproperty 'MS_Description', '消息标识。关联到dist.Message表。', 'Schema', dist, 'table', CertificateMessage, 'column', MessageId
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型参数标识。关联到core.Certificate表。', 'Schema', dist, 'table', CertificateMessage, 'column', CertificateId
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型名称。', 'Schema', dist, 'table', CertificateMessage, 'column', Category
;

EXEC sp_addextendedproperty 'MS_Description', '是否公用。1/0。', 'Schema', dist, 'table', CertificateMessage, 'column', IsPublic
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型参数表。', 'Schema', core, 'table', Certificate
;
EXEC sp_addextendedproperty 'MS_Description', '证件类型标识。', 'Schema', core, 'table', Certificate, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '证件类型名称。', 'Schema', core, 'table', Certificate, 'column', Category
;

EXEC sp_addextendedproperty 'MS_Description', '是否公用。1/0。', 'Schema', core, 'table', Certificate, 'column', IsPublic
;

EXEC sp_addextendedproperty 'MS_Description', '预订数据工作流。', 'Schema', dist, 'table', SubscribeWorkflow
;
EXEC sp_addextendedproperty 'MS_Description', '工作流标识。关联到core.Base表。', 'Schema', dist, 'table', SubscribeWorkflow, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '前一个工作流标识。', 'Schema', dist, 'table', SubscribeWorkflow, 'column', PrevWfID
;

EXEC sp_addextendedproperty 'MS_Description', '消息标识。关联到dist.Message表。', 'Schema', dist, 'table', SubscribeWorkflow, 'column', MessageId
;

EXEC sp_addextendedproperty 'MS_Description', '预订通道标识。关联到dist.SubscribeChannel表。', 'Schema', dist, 'table', SubscribeWorkflow, 'column', ChannelId
;

EXEC sp_addextendedproperty 'MS_Description', '工作流状态。1：待发送；2：提取到队列；3：已发送；4：等待补发；5：放弃；65535：终止。', 'Schema', dist, 'table', SubscribeWorkflow, 'column', Status
;

EXEC sp_addextendedproperty 'MS_Description', '预订数据通道。', 'Schema', dist, 'table', SubscribeChannel
;
EXEC sp_addextendedproperty 'MS_Description', '预定通道标记。关联到core.Base表。', 'Schema', dist, 'table', SubscribeChannel, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '预订服务器标识。关联到dist.SubscribeServer表。', 'Schema', dist, 'table', SubscribeChannel, 'column', ServerId
;

EXEC sp_addextendedproperty 'MS_Description', '需要预订的数据发布事件标识。关联到dist.PublishEvent表。', 'Schema', dist, 'table', SubscribeChannel, 'column', PublishMsgId
;

EXEC sp_addextendedproperty 'MS_Description', '接收预订数据的MSMQ私有队列路径。', 'Schema', dist, 'table', SubscribeChannel, 'column', MessageQueuePath
;

EXEC sp_addextendedproperty 'MS_Description', '是否为事务性的私有队列。1/0。', 'Schema', dist, 'table', SubscribeChannel, 'column', IsTransactional
;

EXEC sp_addextendedproperty 'MS_Description', '最大补发次数。1/0。', 'Schema', dist, 'table', SubscribeChannel, 'column', MaxReissueTimes
;

EXEC sp_addextendedproperty 'MS_Description', '发送失败后，是否允许加入死信。', 'Schema', dist, 'table', SubscribeChannel, 'column', Deadletter
;

EXEC sp_addextendedproperty 'MS_Description', '是否需要各种状态回执。1/0。', 'Schema', dist, 'table', SubscribeChannel, 'column', ReceiptRequired
;

EXEC sp_addextendedproperty 'MS_Description', '预订数据发送超时分钟数。超过则直接加入死信或者放弃。', 'Schema', dist, 'table', SubscribeChannel, 'column', TimeoutMins
;

EXEC sp_addextendedproperty 'MS_Description', '预订服务器信息表。', 'Schema', dist, 'table', SubscribeServer
;
EXEC sp_addextendedproperty 'MS_Description', '预订服务器唯一标识。关联到core.Base表。', 'Schema', dist, 'table', SubscribeServer, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '所属的分数据中心标识。关联到core.DataCenter表。', 'Schema', dist, 'table', SubscribeServer, 'column', CenterId
;

EXEC sp_addextendedproperty 'MS_Description', '服务器机器名。', 'Schema', dist, 'table', SubscribeServer, 'column', MachineName
;

EXEC sp_addextendedproperty 'MS_Description', 'v4版本的IP地址。', 'Schema', dist, 'table', SubscribeServer, 'column', IPv4
;

EXEC sp_addextendedproperty 'MS_Description', 'v6版本的IP地址。', 'Schema', dist, 'table', SubscribeServer, 'column', IPv6
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置分发消息表。仅分发公开的SSO的配置。', 'Schema', dist, 'table', SsoConfigurationMessage
;
EXEC sp_addextendedproperty 'MS_Description', '分发的消息标识。关联到dist.Message表。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', MessageId
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置标识。关联到sso.Configuration表。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', ConfigId
;

EXEC sp_addextendedproperty 'MS_Description', '配置名称。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', ConfigName
;

EXEC sp_addextendedproperty 'MS_Description', '是否启用开放式API。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', StartOpenAPI
;

EXEC sp_addextendedproperty 'MS_Description', '是否可以继承。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', CanInherit
;

EXEC sp_addextendedproperty 'MS_Description', '继承自的配置标识。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', BaseId
;

EXEC sp_addextendedproperty 'MS_Description', '令牌标记名称。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', TokenMark
;

EXEC sp_addextendedproperty 'MS_Description', '令牌失效分钟数。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', TokenExpiredMins
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO验证是否是必须的。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', SsoRequired
;

EXEC sp_addextendedproperty 'MS_Description', '是否显示注册链接。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', ShowRegisterLink
;

EXEC sp_addextendedproperty 'MS_Description', '注册链接地址。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', RegisterLinkUrl
;

EXEC sp_addextendedproperty 'MS_Description', '默认语言。', 'Schema', dist, 'table', SsoConfigurationMessage, 'column', DefaultLanguage
;

EXEC sp_addextendedproperty 'MS_Description', '分发事件基本消息数据。', 'Schema', dist, 'table', Message
;
EXEC sp_addextendedproperty 'MS_Description', '消息标识。关联到core.Base表。', 'Schema', dist, 'table', Message, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '关联的事件表示。关联到dist.Event表。', 'Schema', dist, 'table', Message, 'column', EventId
;

EXEC sp_addextendedproperty 'MS_Description', '是否准备完毕。1/0。', 'Schema', dist, 'table', Message, 'column', Completed
;

EXEC sp_addextendedproperty 'MS_Description', '消息的动作。''C'':创建;‘U''：更新；''R''：逻辑移除；''D''：物理移除。', 'Schema', dist, 'table', Message, 'column', Action
;

EXEC sp_addextendedproperty 'MS_Description', '对外发布的分发事件类型。', 'Schema', dist, 'table', PublishEvent
;
EXEC sp_addextendedproperty 'MS_Description', '分发事件类型唯一标识。关联到core.Base表。', 'Schema', dist, 'table', PublishEvent, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', 'SQL命令模板。', 'Schema', dist, 'table', PublishEvent, 'column', CmdTemplate
;

EXEC sp_addextendedproperty 'MS_Description', '数据分发事件表。', 'Schema', dist, 'table', Event
;
EXEC sp_addextendedproperty 'MS_Description', '分发事件标识。', 'Schema', dist, 'table', Event, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '分发事件类型标识。关联到dist.PublishEvent表。', 'Schema', dist, 'table', Event, 'column', TypeId
;

EXEC sp_addextendedproperty 'MS_Description', '获取分发数据的SQL命令文本。', 'Schema', dist, 'table', Event, 'column', Cmd
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心对象标识转移关系表。', 'Schema', core, 'table', IDTransfer
;
EXEC sp_addextendedproperty 'MS_Description', '转移关系标识。关联到core.Base表。', 'Schema', core, 'table', IDTransfer, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心标识。关联到core.DataCenter表。', 'Schema', core, 'table', IDTransfer, 'column', CenterId
;

EXEC sp_addextendedproperty 'MS_Description', '原始的标识。', 'Schema', core, 'table', IDTransfer, 'column', SourceId
;

EXEC sp_addextendedproperty 'MS_Description', '在当前数据中心中的标识。关联到core.Base表。', 'Schema', core, 'table', IDTransfer, 'column', InternalId
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心信息表。', 'Schema', core, 'table', DataCeter
;
EXEC sp_addextendedproperty 'MS_Description', '数据中心在本机中的标识。关联到core.Base表。', 'Schema', core, 'table', DataCeter, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '数据中心英文代码。', 'Schema', core, 'table', DataCeter, 'column', Code
;

EXEC sp_addextendedproperty 'MS_Description', '是否为总数据中心。1/0。只能有一个总数据中心。', 'Schema', core, 'table', DataCeter, 'column', IsGlobal
;

EXEC sp_addextendedproperty 'MS_Description', '总数据中心的MAC地址。', 'Schema', core, 'table', DataCeter, 'column', Mac
;

EXEC sp_addextendedproperty 'MS_Description', '应用注册信息。', 'Schema', sso, 'table', Application
;
EXEC sp_addextendedproperty 'MS_Description', '应用信息标识。关联到core.Base表。', 'Schema', sso, 'table', Application, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置标识。关联到sso.Configuration表。', 'Schema', sso, 'table', Application, 'column', ConfigId
;

EXEC sp_addextendedproperty 'MS_Description', '应用名称。', 'Schema', sso, 'table', Application, 'column', AppName
;

EXEC sp_addextendedproperty 'MS_Description', '是否为测试版的应用。1/0。', 'Schema', sso, 'table', Application, 'column', IsBeta
;

EXEC sp_addextendedproperty 'MS_Description', '用于获取服务信息的邮件地址。', 'Schema', sso, 'table', Application, 'column', EmailOfService
;

EXEC sp_addextendedproperty 'MS_Description', 'SSO配置信息。', 'Schema', sso, 'table', Configuration
;
EXEC sp_addextendedproperty 'MS_Description', '配置信息标识。关联到core.Base表。', 'Schema', sso, 'table', Configuration, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '配置标识名称。', 'Schema', sso, 'table', Configuration, 'column', ConfigName
;

EXEC sp_addextendedproperty 'MS_Description', '是否启用开放API访问。1/0。', 'Schema', sso, 'table', Configuration, 'column', StartOpenAPI
;

EXEC sp_addextendedproperty 'MS_Description', '是否为私有配置。1/0。', 'Schema', sso, 'table', Configuration, 'column', IsPrivate
;

EXEC sp_addextendedproperty 'MS_Description', '是否可以继承。1/0。', 'Schema', sso, 'table', Configuration, 'column', CanInherit
;

EXEC sp_addextendedproperty 'MS_Description', '继承的配置标识。', 'Schema', sso, 'table', Configuration, 'column', BaseId
;

EXEC sp_addextendedproperty 'MS_Description', '用于保存令牌数据的键名称。', 'Schema', sso, 'table', Configuration, 'column', TokenMark
;

EXEC sp_addextendedproperty 'MS_Description', '令牌超时分钟数。', 'Schema', sso, 'table', Configuration, 'column', TokenExpiredMins
;

EXEC sp_addextendedproperty 'MS_Description', '退出后，下次必须重新登录。', 'Schema', sso, 'table', Configuration, 'column', SsoRequired
;

EXEC sp_addextendedproperty 'MS_Description', '是否显示注册链接。', 'Schema', sso, 'table', Configuration, 'column', ShowRegisterLink
;

EXEC sp_addextendedproperty 'MS_Description', '注册链接地址。', 'Schema', sso, 'table', Configuration, 'column', RegisterLinkUrl
;

EXEC sp_addextendedproperty 'MS_Description', '默认的语言LCID。', 'Schema', sso, 'table', Configuration, 'column', DefaultLanguage
;

EXEC sp_addextendedproperty 'MS_Description', '对象基本属性信息表。', 'Schema', core, 'table', Base
;
EXEC sp_addextendedproperty 'MS_Description', '对象唯一标识。', 'Schema', core, 'table', Base, 'column', Id
;

EXEC sp_addextendedproperty 'MS_Description', '对象的开放标识。', 'Schema', core, 'table', Base, 'column', PublicId
;

EXEC sp_addextendedproperty 'MS_Description', '是否可用。1/0。', 'Schema', core, 'table', Base, 'column', Enabled
;

EXEC sp_addextendedproperty 'MS_Description', '是否已经被逻辑移除。1/0。', 'Schema', core, 'table', Base, 'column', IsRemoved
;

EXEC sp_addextendedproperty 'MS_Description', '是否可见。1/0。', 'Schema', core, 'table', Base, 'column', Visible
;

EXEC sp_addextendedproperty 'MS_Description', '是否为默认的对象。1/0。', 'Schema', core, 'table', Base, 'column', IsDefault
;

EXEC sp_addextendedproperty 'MS_Description', '是否已经被激活。', 'Schema', core, 'table', Base, 'column', Actived
;

EXEC sp_addextendedproperty 'MS_Description', '排序标记。', 'Schema', core, 'table', Base, 'column', SortId
;

EXEC sp_addextendedproperty 'MS_Description', '版本号。', 'Schema', core, 'table', Base, 'column', Version
;

EXEC sp_addextendedproperty 'MS_Description', '是否被锁定。1/0。', 'Schema', core, 'table', Base, 'column', IsLocked
;

EXEC sp_addextendedproperty 'MS_Description', '是否被冻结。', 'Schema', core, 'table', Base, 'column', IsFrozen
;

EXEC sp_addextendedproperty 'MS_Description', '对象的创建时间。', 'Schema', core, 'table', Base, 'column', CreatedTime
;

EXEC sp_addextendedproperty 'MS_Description', '最后一次被修改的时间。', 'Schema', core, 'table', Base, 'column', LastModifiedTime
;

EXEC sp_addextendedproperty 'MS_Description', '对象信息被修改的次数。', 'Schema', core, 'table', Base, 'column', ModifiedTimes
;

EXEC sp_addextendedproperty 'MS_Description', '扩展的属性。', 'Schema', core, 'table', Base, 'column', ExtendedAttributes
;

EXEC sp_addextendedproperty 'MS_Description', '为了保证兼容性的扩展属性。', 'Schema', core, 'table', Base, 'column', CompatibleExtendedAttributes
;

EXEC sp_addextendedproperty 'MS_Description', '描述信息。', 'Schema', core, 'table', Base, 'column', Description
;

EXEC sp_addextendedproperty 'MS_Description', '备注信息。', 'Schema', core, 'table', Base, 'column', Comments
;
